import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { Button } from '@mui/material'


export default function Home({name, summary}) {
  const router = useRouter();
  return (
    <>
    
      <Head>
        <title>My portofolio VGH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.Home}>
        <h1 className={styles.Name}>{name}</h1>
        <div className={styles.Summary}>{summary}</div>
        <div>
          <Button variant='contained' size='large' onClick={()=> router.push("/projects")}>Projects</Button>
        </div>

      </section>
    </>
  )
}

export async function getStaticProps (){
  return {
    props:{
      name: "Vanesa GH",
      summary: "A mechanical electrical engineer who likes to code"
    },
  };
}
